# Generated by Django 3.0.8 on 2020-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200716_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='facebok',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='twitter',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
