# Generated by Django 3.0.8 on 2020-07-23 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_comment_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='likes',
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
