# Generated by Django 3.0.8 on 2020-07-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200723_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
